import type React from "react";
import { ethers, BrowserProvider, Contract } from "ethers";
import {
  JOB_MARKET_ABI,
  VRT_TOKEN_ABI,
  ESCROW_ABI,
  DISPUTE_RESOLUTION_ABI,
  USER_PROFILE_ABI,
  GOVERNANCE_ABI,
  BOUNTY_BOARD_ABI,
  SUB_CONTRACTING_ABI,
} from "./abis";

// ─── Native currency symbol (chain-aware) ──────────────────────────────────────
const NATIVE_CURRENCY_MAP: Record<number, string> = {
  80002: "POL",    // Polygon Amoy
  84532: "ETH",    // Base Sepolia
  11155111: "ETH", // Sepolia
  31337: "ETH",    // Hardhat localhost
};
export const NATIVE_SYMBOL =
  NATIVE_CURRENCY_MAP[Number(process.env.NEXT_PUBLIC_CHAIN_ID || "31337")] || "ETH";

// ─── Contract addresses ────────────────────────────────────────────────────────
// Populated from .env.local generated by the deploy script
export const CONTRACT_ADDRESSES = {
  VRTToken:          process.env.NEXT_PUBLIC_VRT_TOKEN           || process.env.NEXT_PUBLIC_DFM_TOKEN || "",
  JobMarket:         process.env.NEXT_PUBLIC_JOB_MARKET          || "",
  Escrow:            process.env.NEXT_PUBLIC_ESCROW              || "",
  DisputeResolution: process.env.NEXT_PUBLIC_DISPUTE_RESOLUTION  || "",
  UserProfile:       process.env.NEXT_PUBLIC_USER_PROFILE        || "",
  Governance:        process.env.NEXT_PUBLIC_GOVERNANCE           || "",
  BountyBoard:       process.env.NEXT_PUBLIC_BOUNTY_BOARD         || "",
  SubContracting:    process.env.NEXT_PUBLIC_SUB_CONTRACTING      || "",
};

// ─── Status helpers ────────────────────────────────────────────────────────────
export const JOB_STATUS: Record<number, string> = {
  0: "Open",
  1: "In Progress",
  2: "Completed",
  3: "Cancelled",
  4: "Disputed",
  5: "Delivered",
};

type ThemeColors = { successBg: string; successText: string; infoBg: string; infoText: string; mutedFg: string; muted: string; dangerBg: string; dangerText: string; warningBg: string; warningText: string; badgeBg: string; badgeText: string; primaryLight: string; primaryFg: string; [k: string]: string };

export function jobStatusStyle(status: number, c: ThemeColors): React.CSSProperties {
  const map: Record<number, React.CSSProperties> = {
    0: { background: c.successBg, color: c.successText },
    1: { background: c.infoBg, color: c.infoText },
    2: { background: c.muted + "22", color: c.mutedFg },
    3: { background: c.dangerBg, color: c.dangerText },
    4: { background: c.warningBg, color: c.warningText },
    5: { background: c.badgeBg, color: c.badgeText },
  };
  return map[status] ?? {};
}

export const DISPUTE_STATUS: Record<number, string> = {
  0: "Active",
  1: "Response Period",
  2: "Voting Phase",
  3: "Resolved",
  4: "Auto-Resolved",
  5: "Withdrawn",
  6: "Escalated to Admin",
};

export function disputeStatusStyle(status: number, c: ThemeColors): React.CSSProperties {
  const map: Record<number, React.CSSProperties> = {
    0: { background: c.warningBg, color: c.warningText },
    1: { background: c.warningBg, color: c.warningText },
    2: { background: c.infoBg, color: c.infoText },
    3: { background: c.successBg, color: c.successText },
    4: { background: c.muted + "22", color: c.mutedFg },
    5: { background: c.muted + "22", color: c.mutedFg },
    6: { background: c.dangerBg, color: c.dangerText },
  };
  return map[status] ?? {};
}

export const BOUNTY_STATUS: Record<number, string> = {
  0: "Open",
  1: "Completed",
  2: "Cancelled",
};

export const SUBMISSION_STATUS: Record<number, string> = {
  0: "Pending",
  1: "Approved",
  2: "Rejected",
};

export const SUB_CONTRACT_STATUS: Record<number, string> = {
  0: "Open",
  1: "Active",
  2: "Delivered",
  3: "Completed",
  4: "Disputed",
  5: "Cancelled",
};

export const TIER_NAMES: Record<number, string> = {
  0: "Bronze",
  1: "Silver",
  2: "Gold",
  3: "Platinum",
};

export const TIER_COLORS: Record<number, string> = {
  0: "text-amber-700",
  1: "text-gray-400",
  2: "text-yellow-500",
  3: "text-purple-400",
};

// ─── Chat storage key helpers ────────────────────────────────────────────────
export function chatKey(jobId: bigint | string): string {
  const addr = CONTRACT_ADDRESSES.JobMarket || "local";
  return `dfm_chat_${addr}_${jobId}`;
}
export function chatReadKey(jobId: bigint | string, address: string): string {
  const addr = CONTRACT_ADDRESSES.JobMarket || "local";
  return `dfm_chat_read_${addr}_${jobId}_${address.toLowerCase()}`;
}

// ─── Contract getters ──────────────────────────────────────────────────────────
type SP = ethers.Signer | ethers.Provider;

export function getJobMarket(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.JobMarket, JOB_MARKET_ABI, sp);
}

export function getVRTToken(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.VRTToken, VRT_TOKEN_ABI, sp);
}

export function getEscrow(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.Escrow, ESCROW_ABI, sp);
}

export function getDisputeResolution(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.DisputeResolution, DISPUTE_RESOLUTION_ABI, sp);
}

export function getUserProfile(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.UserProfile, USER_PROFILE_ABI, sp);
}

export function getGovernance(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.Governance, GOVERNANCE_ABI, sp);
}

export function getBountyBoard(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.BountyBoard, BOUNTY_BOARD_ABI, sp);
}

export function getSubContracting(sp: SP) {
  return new Contract(CONTRACT_ADDRESSES.SubContracting, SUB_CONTRACTING_ABI, sp);
}

// ─── Provider helper ───────────────────────────────────────────────────────────
export async function getProvider(): Promise<BrowserProvider> {
  if (typeof window === "undefined" || !window.ethereum) {
    throw new Error("MetaMask not detected. Please install MetaMask.");
  }
  return new BrowserProvider(window.ethereum);
}

export function formatEth(wei: bigint): string {
  return parseFloat(ethers.formatEther(wei)).toFixed(4);
}

export function formatVrt(wei: bigint): string {
  return parseFloat(ethers.formatEther(wei)).toFixed(2);
}

export function formatDate(timestamp: bigint | number): string {
  return new Date(Number(timestamp) * 1000).toLocaleDateString();
}

export function formatDateTime(timestamp: bigint | number): string {
  return new Date(Number(timestamp) * 1000).toLocaleString();
}

export function shortenAddress(addr: string | undefined | null): string {
  if (!addr || addr.length < 10) return addr ?? "0x????";
  return addr.slice(0, 6) + "…" + addr.slice(-4);
}

export function timeRemaining(deadline: bigint | number): string {
  const now = Math.floor(Date.now() / 1000);
  const diff = Number(deadline) - now;
  if (diff <= 0) return "Expired";
  const days = Math.floor(diff / 86400);
  const hours = Math.floor((diff % 86400) / 3600);
  if (days > 0) return `${days}d ${hours}h`;
  const mins = Math.floor((diff % 3600) / 60);
  return hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
}
